---
title: "AM230 Actuarial Statistics I"
format: 
  html:
    toc: true
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

[Syllabus](syllabus.html)

| Date        | Section/Topic                     | Notes                                                                                                                                                                                                                | Homework                                               |
|------------------|------------------|-------------------|------------------|
| **Week 1**  |                                   |                                                                                                                                                                                                                      |                                                        |
| 6/9         | 2.4. Probability and Statistics   | [Note](note230_1_annotated.pdf)                                                                                                                                                                                      |                                                        |
| 8/9         | 2.4. Probability and Statistics   | [Note](note230_2_annotated.pdf)                                                                                                                                                                                      | [2.11. 2.12, 2.13, 2.18, 2.19](hw/hw230_section24.pdf) |
| **Week 2**  |                                   |                                                                                                                                                                                                                      |                                                        |
| 11/9        | 2.7. Conditional Probability      | [Note](note230_3_annotated.pdf)                                                                                                                                                                                      |                                                        |
| 13/9        | 2.7. Conditional Probability      | [Note](note230_4_annotated.pdf), [Homework](hw230.pdf)                                                                                                                                                               | [2.71ab, 2.72, 2.74, 2.77](hw/hw230_section27.pdf)     |
| 15/9        | 2.8. Some Laws of Probability     | [Note](note230_5_annotated.pdf),                                                                                                                                                                                     | [2.85, 2.93, 2.96](hw/hw230_section28.pdf)             |
| **Week 3**  |                                   |                                                                                                                                                                                                                      |                                                        |
| 18/9        | 2.10. Bayes' Theorem              | [Note](note230_6_annotated.pdf)                                                                                                                                                                                      |                                                        |
| 20/9        | 2.10. Bayes' Theorem              | [Note](note230_7_annotated.pdf)                                                                                                                                                                                      | [hw](hw/hw230_section210.pdf)                          |
| 22/9        | Review for Exam 1                 | [Practice 1](exams/230_exam1_practice1.html), [Solution](exams/230_exam1_practice1_sol.pdf) <br> [Practice 2](exams/230_exam1_practice2.html), [Solution](exams/230_exam1_practice2_sol.pdf)                         |                                                        |
| **Week 4**  |                                   |                                                                                                                                                                                                                      |                                                        |
| 25/9        | Exam 1                            |                                                                                                                                                                                                                      |                                                        |
| 27/9        | 3.2. Discrete Random Variable     | [Note](230_chap3_1.pdf)                                                                                                                                                                                              |                                                        |
| 29/9        | 3.3. Expectation and Variance     | [Note](230_chap3_2.pdf)                                                                                                                                                                                              | [Homework](hw/hw_section33_1.pdf)                      |
| **Week 5**  |                                   |                                                                                                                                                                                                                      |                                                        |
| 10/2        | 3.3. Expectation and Variance     |                                                                                                                                                                                                                      |                                                        |
| 10/4        | 3.4. Binomial Distribution        | [Note](34.pdf)                                                                                                                                                                                                       |                                                        |
| 10/6        | 3.4. Binomial Distribution        | [Note](34_2.pdf)                                                                                                                                                                                                     | [Homework](hw/hw_section34_1.pdf)                      |
| **Week 6**  |                                   |                                                                                                                                                                                                                      |                                                        |
| 10/11       | 3.5. Geometric Prob. Distribution | [Note](35_1.pdf)                                                                                                                                                                                                     |                                                        |
| 10/13       | 3.5. Geometric Prob. Distribution | [Note]()                                                                                                                                                                                                             | [Homework](hw/hw_section35.pdf)                        |
| **Week 7**  |                                   |                                                                                                                                                                                                                      |                                                        |
| 10/16       | 3.8. Poisson Prob. Distribution   | [Note](chap3.pdf)                                                                                                                                                                                                    |                                                        |
| 10/18       | 3.8. Poisson Prob. Distribution   | [Note](chap3.pdf)                                                                                                                                                                                                    | [Homework](hw/hw_section38.pdf)                        |
| 10/20       | 3.9.                              | [Note](chap3.pdf)                                                                                                                                                                                                    |                                                        |
| **Week 8**  |                                   |                                                                                                                                                                                                                      |                                                        |
| 10/23       | 3.9. MGF                          | [Note](chap3.pdf)                                                                                                                                                                                                    |                                                        |
| 10/25       | 3.11.                             | [Note](chap3_5.pdf)                                                                                                                                                                                                  |                                                        |
| 10/27       | Review for Exam 2                 | [Practice 1](exams/exam2/230_exam2_practice1.html), [Solution](exams/exam2/230_exam2_practice1_sol.pdf) <br> [Practice 2](exams/exam2/230_exam2_practice2.html), [Solution](exams/exam2/230_exam2_practice2_sol.pdf) |                                                        |
| **Week 9**  |                                   |                                                                                                                                                                                                                      |                                                        |
| 10/30       | Exam 2                            |                                                                                                                                                                                                                      |                                                        |
| 11/01       | Chapter 4                         | [Note](chap4.pdf)                                                                                                                                                                                                    |                                                        |
| 11/03       | Chapter 4                         | [Note](chap4.pdf)                                                                                                                                                                                                    |                                                        |
| **Week 10** |                                   |                                                                                                                                                                                                                      |                                                        |
| 11/06       | Chapter 4                         | [Note](chap4.pdf)                                                                                                                                                                                                    | [Homework](hw/hw_section42.pdf)                        |
| 11/08       | 4.2                               | [Note](chap4.pdf)                                                                                                                                                                                                    | [Homework](hw/hw_section43.pdf)                        |
| 11/10       | 4.3                               | [Note](chap4.pdf)                                                                                                                                                                                                    |                                                        |
| **Week 11** |                                   |                                                                                                                                                                                                                      |                                                        |
| 11/13       | 4.3                               | [Note](chap4.pdf)                                                                                                                                                                                                    |                                                        |
| 11/15       | 4.4-4.5                           | [Note](chap4.pdf)                                                                                                                                                                                                    |                                                        |
| 11/17       | 4.6-4.7                           | [Note](chap4.pdf)                                                                                                                                                                                                    | [Homework](hw/hw_section44_47.pdf)                     |
| **Week 12** |                                   |                                                                                                                                                                                                                      |                                                        |
| **Week 13** |                                   |                                                                                                                                                                                                                      |                                                        |
| 11/27       | Exam 3's Review                   | [Practice Exam](exams/exam3/230_exam3_practice1.html), [Solution](exams/exam3/230_exam3_practice_sol.pdf)                                                                                                            |                                                        |
| 11/29       | Exam 3                            |                                                                                                                                                                                                                      |                                                        |
| 12/01       | Chapter 5                         | [Note](chap5.pdf)                                                                                                                                                                                                    |                                                        |
| **Week 14** |                                   |                                                                                                                                                                                                                      |                                                        |
| 12/04       | Chapter 5                         | [Note](chap5.pdf)                                                                                                                                                                                                    |                                                        |
| 12/06       | Chapter 5                         | [Note](chap5.pdf)                                                                                                                                                                                                    |                                                        |
| 12/08       | Final Exam's Review               | [Practice 1](exams/final/230_final_exam_practice1.html), [Solution](exams/final/230_final_exam_practice1_sol.pdf)                                                                                                    |                                                        |
| **Week 15** |                                   |                                                                                                                                                                                                                      |                                                        |
| 12/11       | Final Exam's Review               | [Practice 2](exams/final/230_final_exam_practice2.html), [Solution](exams/final/230_final_exam_practice2_sol.pdf) <br> [Exam 4](exams/exam4/exam4.html) <br> [Mid-term Exams' Solution](midterm.html)                |                                                        |

: {.striped .hover}
